import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Provider from "@/provider/AuthProvider";
import { getServerSession } from "next-auth";
import { Toaster } from "@/components/ui/toaster"
import Sidebar from "@/components/ui/sidebar/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = getServerSession()
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <Provider session={session}>
          <div className="flex gap-4">
            <Sidebar />
            {children}
            <Toaster />
          </div>
        </Provider>
      </body>
    </html>
  );
}
